### ISSUE TITLE
Cross platform tray behavior

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#150]
Tested on windows.
Minimize driveshare-gui to tray. I am getting a nice tray icon. If I restore driveshare-gui the tray icon should still be in the tray like every other icon. Don't remove it.

**Comment by gordonwritescode** [comment]
@littleskunk, I think this a subjective behavior expectation. Personally, I feel that if the app has focus, the user is engaged with it and there is no need to keep the icon in tray (hence "*minimize* to tray").

This should not hold up the v0.5.0 release, so I'm labeling it as a discussion and keeping it in the backlog for now.

**Comment by super3** [comment]
I agree with @littleskunk. When I click on other apps on Windows, they come in focus but stay in tray. I think we should follow what the expected behavior is. 

Oh the flip side @gordonwritescode is right. "*Minimize* to tray" is not really descriptive of the expected behavior. Think we should rename that slightly and do the expected behavior. 

Not sure if this is the expected behavior on Mac of Linux.

**Comment by super3** [comment]
Got a ACK from @littleskunk on Slack. #77 was another issue where on Mac we fixed it to fit the expected behavior. My open ended question is that is this the expected behavior for OSX and Linux. If this is not the case then this should only be a fix for Windows similar to #77.

**Comment by super3** [comment]
Addressed in #159
