### ISSUE TITLE
Constant Update Notification

### ISSUE THREAD

**Issue by trismegistis** [Storj/driveshare-gui#90]
Hi all, I ran Driveshare a couple of times and it hasnt said there was an update. Now it does, I download the 3.4 version, but it seems its the same as the one I have already, and after installing, it still says theres an update available

**Comment by gordonwritescode** [comment]
Hi friend, looks like this is because we are using the version tracked at the `master` branch to notify you that there is an update and `master` is currently tracking `v0.4.1`. Releases have not yet been packaged for all platforms, which why you downloaded the version you already had! :smile: 

The `Updater` class should be changed to look at remote tags instead of what's in master to avoid this in the future. I'll fix this.

**Comment by littleskunk** [comment]
Retest passed. I get only a message if a new release is published. Fix will come with version 0.4.2.

**Comment by trismegistis** [comment]
OK ty
