### ISSUE TITLE
DriveShare is a win x64 ap?

### ISSUE THREAD

**Issue by BogdanGoim** [Storj/driveshare-gui#93]
Sorry I'm an complete noob.
After install, at first run I receive this error message: 
![error](https://cloud.githubusercontent.com/assets/16228706/11693760/56aa65be-9eaf-11e5-9abf-1d6ae60d4ba4.png)
Is this a version for win x64?
Where can I find the version for win x86?

**Comment by littleskunk** [comment]
We released a 64bit binary for dataserv-gui 0.3.4 and linked that binary on http://driveshare.org. Some users are working with 32bit and we added a 32 bit binary later. You can find it here: https://github.com/Storj/driveshare-gui/releases/download/0.3.4-alpha/DriveShare_0.3.4.win32.exe

The next windows binary for 0.4.1 will be 32bit. It will work on 64bit windows as well. 
Mac and Linux have to be 64bit because the framework we are using for the gui does not support anything else.

**Comment by BogdanGoim** [comment]
Thank you littleskunk! It's working :)
